<a href="https://colab.research.google.com/github/uedukondalu/ML-23ag1a66i8/blob/main/ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/sample_data/california_housing_test.csv")

In [3]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [4]:
df.describe()

longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000   
mean   -119.589200    35.63539           28.845333   2599.578667   
std       1.994936     2.12967           12.555396   2155.593332   
min    -124.180000    32.56000            1.000000      6.000000   
25%    -121.810000    33.93000           18.000000   1401.000000   
50%    -118.485000    34.27000           29.000000   2106.000000   
75%    -118.020000    37.69000           37.000000   3129.000000   
max    -114.490000    41.92000           52.000000  30450.000000   

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000   
mean       529.950667   1402.798667   489.91200       3.807272   
std        415.654368   1030.543012   365.42271       1.854512   
min          2.000000      5.000000     2.00000       0.499900   
25%        291.000000    780.000000   273.00000       2.544000   
50%        437.000000   1155.000000   409.50000       3.487150   
75%        636.000000   1742.750000   597.25000       4.656475   
max       5419.000000  11935.000000  4930.00000      15.000100   

       median_house_value  
count          3000.00000  
mean         205846.27500  
std          113119.68747  
min           22500.00000  
25%          121200.00000  
50%          177650.00000  
75%          263975.00000  
max          500001.00000

In [5]:
df.tail()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0

In [6]:
import numpy as np

In [7]:
arr1=np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [8]:
arr2=np.array([[1,2,3,4],
               [6,7,8,9]])
print(arr2)

[[1 2 3 4]
 [6 7 8 9]]


In [9]:
print(arr1.size)
print(arr2.size)

4
8


In [10]:
arr3=np.array([[[2,4,5,7],
               [2,5,7,3]],

               [[3,4,5,6],
               [8,9,7,6]]])
print(arr3)

[[[2 4 5 7]
  [2 5 7 3]]

 [[3 4 5 6]
  [8 9 7 6]]]


In [11]:
print(arr3.size)

16


In [12]:
print(arr1.data)

In [13]:
print(arr2.data)

In [14]:
print(arr3.data)

In [15]:
print(arr1.dtype)

int64


In [16]:
print(arr3.ndim)

3


In [17]:
print(arr1.shape)

(4,)


In [18]:
min=np.min(arr3)
print(min)

2


In [19]:
max=np.max(arr1)
print(max)

4


In [20]:
mean=np.mean(arr2)
print(mean)

5.0


In [21]:
arr4=np.array([[[1,2,3,4],
                [5,6,7,8],
                 [7,8,8,9]],

               [[3,6,7,7],
                [4,5,6,7],
                [3,4,5,6]]])
print(arr4)

[[[1 2 3 4]
  [5 6 7 8]
  [7 8 8 9]]

 [[3 6 7 7]
  [4 5 6 7]
  [3 4 5 6]]]


In [23]:
print(arr4.dtype)

int64


In [24]:
print(arr4.data)

In [26]:
print(arr4.size)

24
